---
- name: Установить необходимые пакеты
  apt:
    name:
      - net-tools
      - dnsutils
      - wget
      - curl
      - mc
      - rsync
    state: present
    update_cache: yes

- name: Изменить имя машины
  hostname:
    name: "{{ ansible_hostname }}"
