---
- name: Установить Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Создать веб-страницу
  copy:
    content: "Hello from {{ ansible_hostname }}!"
    dest: /var/www/html/index.html

- name: Убедиться, что Nginx запущен
  service:
    name: nginx
    state: started
